[params]
  show_related = false  # Disable related content sidebar
  show_reading_time = true
  show_share_buttons = true
  show_post_navigation = true
  show_author = true
  show_date = true
  show_comments = false
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params.mermaid]
  theme = "redux"
  look = "handDrawn"
  layout = "dagre"
  align = "center"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 