[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "https://ashwinkashyap.ai"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://ashwinkashyap.ai"

[context.deploy-preview]
  command = "git submodule update --init --recursive && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "git submodule update --init --recursive && hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

# Form handling configuration
[[redirects]]
  from = "/contact-post-success"
  to = "/contact-post-success/"
  status = 301

[[redirects]]
  from = "/contact-post-success/"
  to = "/contact-post-success/"
  status = 200

# Handle trailing slashes
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true 